main: main_async_actor
training:
  output_dir: null # 输出目录
  from_pretrained: null # actor模型加载路径，megatron core格式
  rollout_model_name: null # rollout推理服务加载路径，huggingface格式
  resume_checkpoint: null # 断点续训actor模型加载目录，megatron core格式
  max_steps: 315 # 最大rollout步数
  save_steps: 5 # 保存ckpt步数
  early_stop_steps: 400 # 训练提前终止步数
  non_persistent_save_steps: 0 # 非持久化保存步数间隔，0表示禁用
  early_stop_steps: 400 # 训练提前终止步数
  save_test_step: 5 # 训练开始后第几步测试保存ckpt，用于防止内存问题
  optim:
    lr: 5e-7 # 学习率
    min_lr: 5e-8 # 衰减最小学习率
    warmup_ratio: 0.03 # warm up步数比例
    scheduler_type: cosine # 学习率衰减类型
    weight_decay: 0.1
    adam_beta1: 0.9
    adam_beta2: 0.98
    adam_eps: 1e-8
  seed: 42
  rollout_batch_size: 256 # 每rollout步样本数量
  global_batch_size: 2048 # 每个训练步的训练数据量
  n_samples: 8 # 每个样本的采样次数
  micro_batch_size: 1 # 训练步micro batch size
  micro_forward_batch_size: 4 # 每个rollout步计算old_actor_logps时的batch size
  max_length: 4096 # 数据处理时prompt + response最大截断长度
  pad_to_max_length: False # True # 在collate_fn里将序列补齐到max_length或动态补齐到每个train batch的最大长度
  dump_experience: True # 是否将采样结果、reward等数据保存
  dump_tensors: False # 是否将tensor保存
  log_level: info # info or debug # 日志级别
  use_outcome_rewards_as_advantages: False # 直接使用reward作为advantage，跳过计算advantage
  skip_zero_reward_sample: True # 训练时跳过归一化得分为0的样本
  policy_loss_limit: 3.25 # 训练时policy loss大小限制，超过则跳过当前样本
  kl_loss_limit: 10 # 训练时kl loss大小限制，超过则跳过当前样本
  mlp_weight_merging_batch_size: 24 # 合并MLP层时每个pp stage的层数批大小
  entropy_loss_threshold: 0.3 # 熵损失生效阈值，低于阈值时在总loss上加入熵损失
  moe_weight_merging_layer_batch_size: 10 # 合并MOE层时每个pp stage的层数批次大小
  moe_weight_merging_expert_batch_size: 10 # 合并MOE层时每层的专家批次大小
algorithm:
  init_kl_coef: 0.0 # 大于等于1e-8时启用reference model
  use_kl_loss: False # 是否使用kl loss
  kl_estimator: k3
  advantage_estimator: 'grpo'
  reward_clip_range: null
  num_repeat_times: 1
  entropy_loss_coef: 0.001 # entropy loss系数，大于0时计算
  policy_loss_coef: 1.0 # RL loss系数，设置为0启用纯蒸馏训练
  negate_kl_loss: False # 是否将kl loss取反
actor:
  tp: 4 # 张量（模型）并行
  pp: 2 # 流水并行
  cp: 1 # 序列并行
  dp: 8 # 数据并行
  moe:
    ep: 1 # 专家并行
    etp: null # 专家张量并行
  weight_update_group_port: 65500
  pack_n_samples: False # 尚未实现
  extra_args:
    - key: recompute-granularity
      value: selective # 选择重计算
    # - key: recompute-granularity
    #   value: full # 完全重计算
    # - key: recompute-method
    #   value: uniform # 完全重计算
    # - key: recompute-num-layers
    #   value: 1 # 重计算层数
reference:
  micro_batch_size: 2 # 前向计算batch size
  tp: 2
  pp: 1
  cp: 1
  dp: 4
  moe:
    ep: 1 # 专家并行
    etp: null # 专家张量并行
  load_path: null # ref模型加载路径
distributed_lock_server:
  port: 13266 # 分布式锁服务器端口
weight_updater_test:
  online_test: False # 在线测试：同步到sglang，离线测试：保存到目录
distillation:
  enabled: False # 是否启用蒸馏训练
  logits_express:
    dtype: fp32 # support: fp32, fp16, bf16
    batch_size: 4 # transfer batch size
    base_port: 45000 # transfer base port
  gkd:
    student_temperature: 1.0
    teacher_temperature: 1.0
    beta: 0.0 # beta of gkd
    seq_kd: False # whether to use sequence-level kd
async_rollout:
  data: '' # 数据集路径
  actor_service_name: actor_model # actor模型服务名称
  teacher_models_registry: null
  services:
    - type: sglang
      name: actor_model
      resource_cfg:
        type: sglang
        is_gpu_resource: True
        base_port: 18580
        num_instances: 4
        params:
          model_path: ''
          tp: 2 # 张量并行
          enable_ep: False # 启用专家并行
          dist_base_port: 23380
      params: 
        health_timeout: 300 # 健康检查超时时间，单位秒
        health_retries: 3 # 健康检查重试次数
        startup_timeout: 300
        max_concurrent_per_resource: 2 # 每个资源最大并发数量
      resources: [] # will be set by headquaters
  workers:
    - type: single_turn
      params:
        n_samples: 8
        max_tokens: 2048
        advantage_estimator: 'grpo'
        stop_token: '<|endoftext|>'
        add_stop_token: true
    - type: math
      handle_data_types: ['math', 'deepscaler']
      params:
        n_samples: 8
        max_tokens: 2048
        advantage_estimator: 'grpo'
        stop_token: '<|endoftext|>'
        add_stop_token: true
        use_cot_reward: true # 是否启用cot奖励
        use_ref_answers: false